### ISSUE TITLE
Error when product name contains a closing parenthesis 

### ISSUE THREAD

**Issue by xpoback** [squeezely/magento2-hyva-plugin#1]
When the product name contains a closing parenthesis the following error appears:

```
VM537:1 Uncaught SyntaxError: Unterminated string in JSON at position 82 (line 1 column 83)
    at JSON.parse (<anonymous>)
    at Object.pushPageEvent (mobigear-folio-12-bookcase-voor-apple-ipad-10-2022.html:725:35)
    at Object.init (mobigear-folio-12-bookcase-voor-apple-ipad-10-2022.html:661:42)
    at mobigear-folio-12-bookcase-voor-apple-ipad-10-2022.html:648:50
```
  
 The reason is that the RegEx in function `pushPageEvent()`  incorrectly matches the escaped JSON string when trying to push a ViewContent event.

Changing the RegEx from `/(?<=\()(.*?)(?=\))/gi` to `/(?<=\()(.*?)}(?=\))/gi` to match until `})` appears seems to resolve the problem but I'm not sure if this doesn't break anything else

**Comment by Frank-Magmodules** [comment]
HI There @xpoback, also on this issue, I'm happy to inform you that this issue is also fixed within the latest [release](https://github.com/squeezely/magento2-hyva-plugin/releases.) Thank you for providing your feedback. I'm closing this issue for now, but please don't hesitate to reach out or reopen it if you have any further questions.
